name: buko
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.9.0
  firebase_storage: ^13.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/buko_icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/buko_icon.png
  adaptive_icon_background: '#07131E'
  adaptive_icon_foreground: assets/buko_icon.png
