const encoder = new TextEncoder();
const PBKDF2_ITERATIONS = 60000;
const TOKEN_TTL_SECONDS = 3600;
function json(data, status = 200) { return new Response(JSON.stringify(data), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store', 'access-control-allow-origin': '*', 'access-control-allow-headers': 'content-type', 'access-control-allow-methods': 'POST, OPTIONS' } }); }
function normalizePhone(value) { let p = String(value ?? '').trim().replace(/[^0-9+]/g, ''); if (p.startsWith('00249')) p = `+${p.slice(2)}`; if (p.startsWith('249')) p = `+${p}`; if (p.startsWith('0') && p.length === 10) p = `+249${p.slice(1)}`; if (!/^\+249\d{9}$/.test(p)) throw new Error('invalid-phone'); return p; }
function b64url(bytes) { let s=''; for (const b of bytes) s += String.fromCharCode(b); return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,''); }
function b64urlDecode(text) { const padded=text.replace(/-/g,'+').replace(/_/g,'/')+'==='.slice((text.length+3)%4); const s=atob(padded); return Uint8Array.from(s,c=>c.charCodeAt(0)); }
function randomBytes(n) { const b=new Uint8Array(n); crypto.getRandomValues(b); return b; }
async function hashPassword(password,salt,iterations=PBKDF2_ITERATIONS) { const key=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveBits']); return new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations,hash:'SHA-256'},key,256)); }
async function encodePassword(password) { const salt=randomBytes(16); return `pbkdf2$${PBKDF2_ITERATIONS}$${b64url(salt)}$${b64url(await hashPassword(password,salt))}`; }
async function verifyPassword(password,stored) { const parts=String(stored).split('$'); if(parts.length!==4||parts[0]!=='pbkdf2')return false; const iterations=Number(parts[1]); if(!Number.isInteger(iterations)||iterations<10000||iterations>500000)return false; const expected=b64urlDecode(parts[3]); const actual=await hashPassword(password,b64urlDecode(parts[2]),iterations); if(actual.length!==expected.length)return false; let diff=0; for(let i=0;i<actual.length;i++)diff|=actual[i]^expected[i]; return diff===0; }
function pemToArrayBuffer(pem) { const clean=String(pem).trim().replace(/\\n/g,'\n').replace(/-----BEGIN PRIVATE KEY-----/g,'').replace(/-----END PRIVATE KEY-----/g,'').replace(/\s/g,''); const binary=atob(clean); const bytes=new Uint8Array(binary.length); for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i); return bytes.buffer; }
async function createFirebaseCustomToken(env,uid,claims={}) { if(!env.FIREBASE_CLIENT_EMAIL||!env.FIREBASE_PRIVATE_KEY)throw new Error('firebase-server-config-missing'); const email=env.FIREBASE_CLIENT_EMAIL.trim(); const now=Math.floor(Date.now()/1000); const header={alg:'RS256',typ:'JWT'}; const payload={iss:email,sub:email,aud:'https://identitytoolkit.googleapis.com/google.identity.identitytoolkit.v1.IdentityToolkit',iat:now,exp:now+TOKEN_TTL_SECONDS,uid,claims}; const unsigned=`${b64url(encoder.encode(JSON.stringify(header)))}.${b64url(encoder.encode(JSON.stringify(payload)))}`; const key=await crypto.subtle.importKey('pkcs8',pemToArrayBuffer(env.FIREBASE_PRIVATE_KEY),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']); return `${unsigned}.${b64url(new Uint8Array(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,encoder.encode(unsigned))))}`; }
async function createSession(env,user) { return {token:await createFirebaseCustomToken(env,user.uid,{admin:user.role==='admin',phone:user.phone}),uid:user.uid,name:user.name,role:user.role,phone:user.phone}; }
function validateCredentials(password) { if(typeof password!=='string'||password.length<6||password.length>128)throw new Error('invalid-password'); }
async function register(env,body) { const phone=normalizePhone(body.phone),password=String(body.password??''),name=String(body.name??'').trim(); validateCredentials(password); if(!name||name.length>80)throw new Error('name-required'); if(await env.DB.prepare('SELECT uid FROM users WHERE phone=?1').bind(phone).first())throw new Error('phone-already-registered'); const uid=`phone_${phone.slice(1)}`; await env.DB.prepare('INSERT INTO users(phone,uid,name,password_hash,role,failed_attempts,locked_until,created_at) VALUES(?1,?2,?3,?4,\'buyer\',0,0,?5)').bind(phone,uid,name,await encodePassword(password),Date.now()).run(); return createSession(env,{phone,uid,name,role:'buyer'}); }
async function login(env,body) { const phone=normalizePhone(body.phone),password=String(body.password??''); validateCredentials(password); const user=await env.DB.prepare('SELECT phone,uid,name,password_hash,role,failed_attempts,locked_until FROM users WHERE phone=?1').bind(phone).first(); if(!user)throw new Error('invalid-credentials'); const now=Date.now(); if(Number(user.locked_until??0)>now)throw new Error('too-many-attempts'); if(!await verifyPassword(password,user.password_hash)){const failed=Number(user.failed_attempts??0)+1,locked=failed>=5?now+900000:0; await env.DB.prepare('UPDATE users SET failed_attempts=?1,locked_until=?2 WHERE phone=?3').bind(locked?0:failed,locked,phone).run(); throw new Error('invalid-credentials');} await env.DB.prepare('UPDATE users SET failed_attempts=0,locked_until=0 WHERE phone=?1').bind(phone).run(); return createSession(env,user); }
async function bootstrapAdmin(env,body) { if(!env.ADMIN_BOOTSTRAP_SECRET||body.secret!==env.ADMIN_BOOTSTRAP_SECRET)throw new Error('forbidden'); const phone=normalizePhone(body.phone),password=String(body.password??''),name=String(body.name??'BUKO Admin').trim()||'BUKO Admin'; validateCredentials(password); const uid=`phone_${phone.slice(1)}`; await env.DB.prepare(`INSERT INTO users(phone,uid,name,password_hash,role,failed_attempts,locked_until,created_at) VALUES(?1,?2,?3,?4,'admin',0,0,?5) ON CONFLICT(phone) DO UPDATE SET uid=excluded.uid,name=excluded.name,password_hash=excluded.password_hash,role='admin',failed_attempts=0,locked_until=0`).bind(phone,uid,name,await encodePassword(password),Date.now()).run(); return {ok:true,phone,uid,role:'admin'}; }
async function selfTestFirebase(env,body) { if(!env.ADMIN_BOOTSTRAP_SECRET||body.secret!==env.ADMIN_BOOTSTRAP_SECRET)throw new Error('forbidden'); if(!env.FIREBASE_API_KEY)throw new Error('firebase-api-key-missing'); const token=await createFirebaseCustomToken(env,'buko_self_test',{selfTest:true}); const r=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken?key=${encodeURIComponent(env.FIREBASE_API_KEY)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,returnSecureToken:true})}); if(r.ok)return {ok:true}; let detail='firebase-token-rejected'; try{const x=await r.json(); detail=x?.error?.message||detail;}catch(_){} throw new Error(`firebase-self-test:${detail}`); }
async function selfTestAdmin(env,body) { if(!env.ADMIN_BOOTSTRAP_SECRET||body.secret!==env.ADMIN_BOOTSTRAP_SECRET)throw new Error('forbidden'); const user=await env.DB.prepare('SELECT phone,uid,role FROM users WHERE phone=?1').bind('+249909976346').first(); if(!user||user.role!=='admin')throw new Error('admin-not-provisioned'); return {ok:true,phone:user.phone,uid:user.uid,role:user.role}; }
export default {async fetch(request,env){ if(request.method==='OPTIONS')return json({ok:true}); if(request.method!=='POST')return json({error:'method-not-allowed'},405); try{const url=new URL(request.url),body=await request.json(); if(url.pathname==='/auth/register')return json(await register(env,body)); if(url.pathname==='/auth/login')return json(await login(env,body)); if(url.pathname==='/auth/bootstrap-admin')return json(await bootstrapAdmin(env,body)); if(url.pathname==='/auth/self-test')return json(await selfTestFirebase(env,body)); if(url.pathname==='/auth/admin-self-test')return json(await selfTestAdmin(env,body)); return json({error:'not-found'},404);}catch(e){const code=e instanceof Error?e.message:'server-error'; const status=code==='forbidden'?403:code==='phone-already-registered'||code==='invalid-credentials'||code==='invalid-phone'||code==='invalid-password'||code==='name-required'||code==='admin-not-provisioned'?400:code==='too-many-attempts'?429:500; return json({error:code},status);} } };
