import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

const adminCode = 'BUKO-ADMIN-2026';
const navy = Color(0xFF0D1B2A), green = Color(0xFF22C55E), yellow = Color(0xFFFFC107), blue = Color(0xFF2563EB);

class Car { final String name, price, city, type, seller; final int year; const Car(this.name,this.year,this.price,this.city,this.type,{this.seller='BUKO'}); }
class User { final String name,email,password,role; User(this.name,this.email,this.password,this.role); }
class PendingAd { final Car car; PendingAd(this.car); }
const carsSeed = <Car>[
  Car('مرسيدس C 180',2020,'880,000 ج.م','القاهرة','سيدان'), Car('كيا سبورتاج',2019,'720,000 ج.م','الجيزة','دفع رباعي'),
  Car('هيونداي النترا',2021,'690,000 ج.م','الإسكندرية','سيدان'), Car('تويوتا كورولا',2020,'760,000 ج.م','القاهرة','سيدان'), Car('BMW X3',2021,'1,600,000 ج.م','الجيزة','دفع رباعي')
];

void main()=>runApp(const BukoApp());
class BukoApp extends StatelessWidget { const BukoApp({super.key}); @override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'BUKO',theme:ThemeData(useMaterial3:true,scaffoldBackgroundColor:navy,colorScheme:ColorScheme.fromSeed(seedColor:green,brightness:Brightness.dark)),home:const Splash()); }
class Splash extends StatefulWidget { const Splash({super.key}); @override State<Splash> createState()=>_SplashState(); }
class _SplashState extends State<Splash> with SingleTickerProviderStateMixin { late final a=AnimationController(vsync:this,duration:const Duration(milliseconds:900))..forward(); @override void initState(){super.initState();Future.delayed(const Duration(milliseconds:2300),(){if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const Home()));});} @override void dispose(){a.dispose();super.dispose();} @override Widget build(BuildContext c)=>Scaffold(backgroundColor:Colors.black,body:Center(child:FadeTransition(opacity:a,child:Column(mainAxisSize:MainAxisSize.min,children:[SvgPicture.asset('assets/images/buko_logo.svg',width:330,height:205),const SizedBox(height:20),const Text('حبابك عشرة',style:TextStyle(color:green,fontSize:36,fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('أهلاً بك في BUKO',style:TextStyle(color:Colors.white70,fontSize:17)),const SizedBox(height:24),const CircularProgressIndicator(color:green)]))));} }

class Home extends StatefulWidget { const Home({super.key}); @override State<Home> createState()=>_HomeState(); }
class _HomeState extends State<Home> {
  int tab=0; String q='',type='الكل',city='الكل'; User? me; final cars=[...carsSeed]; final fav=<int>{}; final pending=<PendingAd>[]; final users=<User>[];
  bool get seller=>me?.role=='seller';
  List<int> get filtered=>List.generate(cars.length,(i)=>i).where((i){final x=cars[i],s=q.trim().toLowerCase();return(s.isEmpty||'${x.name} ${x.city} ${x.type}'.toLowerCase().contains(s))&&(type=='الكل'||x.type==type)&&(city=='الكل'||x.city==city);}).toList();
  @override Widget build(BuildContext c){final pages=[home(),explore(),Sell(seller:seller,name:me?.name,onSubmit:addPending),favorites(),account()];return Directionality(textDirection:TextDirection.rtl,child:Scaffold(body:SafeArea(child:pages[tab]),bottomNavigationBar:NavigationBar(backgroundColor:Colors.white,selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined,color:Colors.black54),selectedIcon:Icon(Icons.home,color:green),label:'الرئيسية'),NavigationDestination(icon:Icon(Icons.search,color:Colors.black54),label:'استكشاف'),NavigationDestination(icon:Icon(Icons.add_circle_outline,color:Colors.black54),selectedIcon:Icon(Icons.add_circle,color:green),label:'بيع سيارتك'),NavigationDestination(icon:Icon(Icons.favorite_border,color:Colors.black54),selectedIcon:Icon(Icons.favorite,color:Colors.red),label:'المفضلة'),NavigationDestination(icon:Icon(Icons.person_outline,color:Colors.black54),selectedIcon:Icon(Icons.person,color:green),label:'حسابي')]));}
  Widget home()=>ListView(padding:const EdgeInsets.all(16),children:[Row(children:[IconButton(onPressed:(){},icon:const Icon(Icons.notifications_none)),const Spacer(),SvgPicture.asset('assets/images/buko_logo.svg',width:145,height:62),const Spacer(),IconButton(onPressed:()=>setState(()=>tab=4),icon:const Icon(Icons.menu))]),Container(height:175,padding:const EdgeInsets.all(20),decoration:BoxDecoration(borderRadius:BorderRadius.circular(24),gradient:const LinearGradient(colors:[Color(0xFF19344A),Color(0xFF07131E)])),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('اعثر على سيارتك',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900)),Text('المستعملة بثقة',style:TextStyle(fontSize:22,color:yellow,fontWeight:FontWeight.w900)),SizedBox(height:8),Text('آلاف السيارات بإنتظارك',style:TextStyle(color:Colors.white70))])),const SizedBox(height:12),search(),const SizedBox(height:12),advanced(),section('السيارات المميزة'),SizedBox(height:210,child:ListView(scrollDirection:Axis.horizontal,children:filtered.take(4).map(featured).toList())),section('أحدث السيارات'),...filtered.take(4).map(card)]);
  Widget search()=>TextField(onChanged:(v)=>setState(()=>q=v),onSubmitted:(_)=>setState(()=>tab=1),style:const TextStyle(color:Colors.black87),decoration:InputDecoration(filled:true,fillColor:Colors.white,prefixIcon:const Icon(Icons.search,color:Colors.black54),suffixIcon:IconButton(onPressed:filters,icon:const Icon(Icons.tune,color:navy)),hintText:'إبحث عن ماركة أو موديل أو كلمة مفتاحية...',hintStyle:const TextStyle(color:Colors.black45),border:OutlineInputBorder(borderRadius:BorderRadius.all(Radius.circular(17)),borderSide:BorderSide.none)));
  Widget advanced()=>Container(padding:const EdgeInsets.all(13),decoration:BoxDecoration(color:const Color(0xFF14283A),borderRadius:BorderRadius.circular(20)),child:Column(children:[Row(children:[const Text('بحث متقدم',style:TextStyle(fontSize:17,fontWeight:FontWeight.bold)),const Spacer(),IconButton(onPressed:filters,icon:const Icon(Icons.tune))]),Row(children:[Expanded(child:box('الماركة','اختر الماركة')),const SizedBox(width:8),Expanded(child:box('النوع',type))]),const SizedBox(height:8),Row(children:[Expanded(child:box('السعر من','أدنى سعر')),const SizedBox(width:8),Expanded(child:box('السعر إلى','أقصى سعر'))]),const SizedBox(height:8),Row(children:[Expanded(child:box('المحافظة',city)),const SizedBox(width:8),Expanded(child:box('نوع الوقود','الكل'))]),const SizedBox(height:10),SizedBox(width:double.infinity,child:FilledButton.icon(style:FilledButton.styleFrom(backgroundColor:yellow,foregroundColor:Colors.black),onPressed:()=>setState(()=>tab=1),icon:const Icon(Icons.search),label:const Text('بحث'))]));
  Widget box(String a,String b)=>Container(padding:const EdgeInsets.all(9),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(13)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(color:Colors.black87,fontSize:10,fontWeight:FontWeight.bold)),Text(b,style:const TextStyle(color:Colors.black87),overflow:TextOverflow.ellipsis)]));
  Widget section(String s)=>Row(children:[Text(s,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const Spacer(),TextButton(onPressed:()=>setState(()=>tab=1),child:const Text('عرض الكل'))]);
  Widget featured(int i){final x=cars[i];return GestureDetector(onTap:()=>details(i),child:Container(width:185,margin:const EdgeInsets.only(left:9),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(17)),child:Column(children:[Container(height:105,decoration:const BoxDecoration(color:Color(0xFFE9EEF1),borderRadius:BorderRadius.vertical(top:Radius.circular(17))),child:Stack(children:[const Center(child:Icon(Icons.directions_car,size:70,color:navy)),Positioned(top:5,right:5,child:Container(color:yellow,padding:const EdgeInsets.all(4),child:const Text('مميز',style:TextStyle(color:Colors.black,fontSize:10)))),Positioned(left:0,top:0,child:IconButton(onPressed:()=>toggle(i),icon:Icon(fav.contains(i)?Icons.favorite:Icons.favorite_border,color:Colors.red))) ])),Padding(padding:const EdgeInsets.all(9),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(x.name,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.black87,fontWeight:FontWeight.bold)),Text('${x.year} • ${x.city}',style:const TextStyle(color:Colors.black54,fontSize:11)),Text(x.price,style:const TextStyle(color:blue,fontWeight:FontWeight.w900))]))])));}
  Widget card(int i){final x=cars[i];return Card(color:Colors.white,child:ListTile(onTap:()=>details(i),leading:const CircleAvatar(backgroundColor:Color(0xFFE8F7ED),child:Icon(Icons.directions_car,color:green)),title:Text(x.name,style:const TextStyle(color:Colors.black87,fontWeight:FontWeight.bold)),subtitle:Text('${x.year} • ${x.city} • ${x.type}',style:const TextStyle(color:Colors.black54)),trailing:Text(x.price,style:const TextStyle(color:blue,fontWeight:FontWeight.bold))));}
  Widget explore()=>ListView(padding:const EdgeInsets.all(16),children:[const Text('استكشاف السيارات',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:12),search(),Row(children:[Chip(label:Text(type)),Chip(label:Text(city)),const Spacer(),IconButton.filled(onPressed:filters,icon:const Icon(Icons.filter_list))]),...filtered.map(card)]);
  Widget favorites()=>ListView(padding:const EdgeInsets.all(16),children:[const Text('المفضلة',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),if(fav.isEmpty)const Padding(padding:EdgeInsets.all(30),child:Center(child:Text('لم تحفظ أي سيارة بعد'))),...fav.where((i)=>i<cars.length).map(card)]);
  Widget account()=>me==null?ListView(padding:const EdgeInsets.all(18),children:[const Text('حسابي',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const Text('سجّل دخولك أو أنشئ حساباً جديداً',style:TextStyle(color:Colors.white70)),const SizedBox(height:20),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:login,icon:const Icon(Icons.login),label:const Text('تسجيل الدخول'))),OutlinedButton.icon(onPressed:register,icon:const Icon(Icons.person_add),label:const Text('إنشاء حساب'))]):ListView(padding:const EdgeInsets.all(18),children:[const Text('حسابي',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text(me!.name),subtitle:Text(me!.email))),Card(child:ListTile(leading:Icon(seller?Icons.storefront:Icons.shopping_bag,color:green),title:Text(seller?'حساب بائع':'حساب مشتري'),subtitle:Text(seller?'إعلاناتك تخضع لمراجعة الإدارة.':'استكشف السيارات واحفظ المفضلة.'))),ListTile(leading:const Icon(Icons.logout),title:const Text('تسجيل الخروج'),onTap:()=>setState(()=>me=null))]);
  void toggle(int i)=>setState(()=>fav.contains(i)?fav.remove(i):fav.add(i)); void details(int i)=>Navigator.push(context,MaterialPageRoute(builder:(_)=>Details(car:cars[i],favorite:fav.contains(i),onFavorite:()=>toggle(i))));
  void addPending(Car c){if(!seller){snack('أنشئ حساب بائع أولاً');return;}setState(()=>pending.add(PendingAd(c)));snack('تم إرسال الإعلان للمراجعة.');}
  Future<void> login()async{final r=await showDialog<dynamic>(context:context,builder:(_)=>LoginDialog(users:users));if(!mounted||r==null)return;if(r==adminCode){await admin();}else if(r is User)setState(()=>me=r);}
  Future<void> register()async{final r=await showDialog<User>(context:context,builder:(_)=>const RegisterDialog());if(!mounted||r==null)return;if(users.any((u)=>u.email.toLowerCase()==r.email.toLowerCase())){snack('البريد مسجل مسبقاً');return;}setState((){users.add(r);me=r;});}
  Future<void> admin()async{await Navigator.push(context,MaterialPageRoute(builder:(_)=>Admin(pending:pending,users:users,onApprove:(i){final p=pending.removeAt(i);setState(()=>cars.add(p.car));},onReject:(i){pending.removeAt(i);setState((){});},onPost:(c){setState(()=>cars.insert(0,c));snack('تم نشر المنشور مباشرة');})));}
  Future<void> filters()async{var t=type,c=city;await showDialog<void>(context:context,builder:(d)=>AlertDialog(title:const Text('البحث المتقدم'),content:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<String>(initialValue:t,items:const['الكل','سيدان','دفع رباعي','بيك أب'].map((v)=>DropdownMenuItem(value:v,child:Text(v))).toList(),onChanged:(v)=>t=v??t),DropdownButtonFormField<String>(initialValue:c,items:const['الكل','القاهرة','الجيزة','الإسكندرية'].map((v)=>DropdownMenuItem(value:v,child:Text(v))).toList(),onChanged:(v)=>c=v??c)]),actions:[FilledButton(onPressed:(){setState((){type=t;city=c;});Navigator.pop(d);},child:const Text('تطبيق'))]));}
  void snack(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));
}

class LoginDialog extends StatefulWidget{final List<User> users;const LoginDialog({super.key,required this.users});@override State<LoginDialog> createState()=>_LoginDialogState();}
class _LoginDialogState extends State<LoginDialog>{final id=TextEditingController(),pw=TextEditingController();String role='buyer',error='';@override void dispose(){id.dispose();pw.dispose();super.dispose();}@override Widget build(BuildContext c)=>AlertDialog(title:const Text('تسجيل الدخول'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:id,decoration:const InputDecoration(labelText:'البريد الإلكتروني أو رمز الإدارة')),TextField(controller:pw,obscureText:true,decoration:const InputDecoration(labelText:'كلمة المرور')),DropdownButtonFormField<String>(initialValue:role,items:const[DropdownMenuItem(value:'buyer',child:Text('مشتري')),DropdownMenuItem(value:'seller',child:Text('بائع'))],onChanged:(v)=>setState(()=>role=v??role)),if(error.isNotEmpty)Text(error,style:const TextStyle(color:Colors.red))]),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('إلغاء')),FilledButton(onPressed:submit,child:const Text('دخول'))]);void submit(){if(id.text.trim()==adminCode){Navigator.pop(context,adminCode);return;}final m=widget.users.where((u)=>u.email.toLowerCase()==id.text.trim().toLowerCase()&&u.password==pw.text&&u.role==role);if(m.isEmpty)setState(()=>error='بيانات الدخول غير صحيحة');else Navigator.pop(context,m.first);}}
class RegisterDialog extends StatefulWidget{const RegisterDialog({super.key});@override State<RegisterDialog> createState()=>_RegisterDialogState();}
class _RegisterDialogState extends State<RegisterDialog>{final n=TextEditingController(),e=TextEditingController(),p=TextEditingController();String role='buyer',error='';@override void dispose(){n.dispose();e.dispose();p.dispose();super.dispose();}@override Widget build(BuildContext c)=>AlertDialog(title:const Text('إنشاء حساب'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'الاسم')),TextField(controller:e,decoration:const InputDecoration(labelText:'البريد الإلكتروني')),TextField(controller:p,obscureText:true,decoration:const InputDecoration(labelText:'كلمة المرور')),DropdownButtonFormField<String>(initialValue:role,items:const[DropdownMenuItem(value:'buyer',child:Text('حساب مشتري')),DropdownMenuItem(value:'seller',child:Text('حساب بائع'))],onChanged:(v)=>setState(()=>role=v??role)),if(error.isNotEmpty)Text(error,style:const TextStyle(color:Colors.red))]),actions:[FilledButton(onPressed:submit,child:const Text('إنشاء'))]);void submit(){if(n.text.trim().length<2||!e.text.contains('@')||p.text.length<4){setState(()=>error='تحقق من البيانات');return;}Navigator.pop(context,User(n.text.trim(),e.text.trim(),p.text,role));}}

class Sell extends StatefulWidget{final bool seller;final String? name;final ValueChanged<Car> onSubmit;const Sell({super.key,required this.seller,required this.name,required this.onSubmit});@override State<Sell> createState()=>_SellState();}
class _SellState extends State<Sell>{final n=TextEditingController(),y=TextEditingController(text:'2024'),p=TextEditingController(),c=TextEditingController(text:'القاهرة');String type='سيدان';@override void dispose(){n.dispose();y.dispose();p.dispose();c.dispose();super.dispose();}@override Widget build(BuildContext x){if(!widget.seller)return const Center(child:Padding(padding:EdgeInsets.all(25),child:Text('قسم البيع مخصص لحسابات البائعين. أنشئ حساب بائع من حسابي أولاً.',textAlign:TextAlign.center,style:TextStyle(fontSize:19))));return ListView(padding:const EdgeInsets.all(18),children:[const Text('بيع سيارتك',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),Text('البائع: ${widget.name}'),const Card(child:ListTile(leading:Icon(Icons.verified_user,color:green),title:Text('موافقة الإدارة مطلوبة'),subtitle:Text('لن يظهر الإعلان للعامة قبل الموافقة.'))),field(n,'الماركة والموديل'),field(y,'السنة'),field(p,'السعر'),field(c,'المدينة'),DropdownButtonFormField<String>(initialValue:type,items:const['سيدان','دفع رباعي','بيك أب'].map((v)=>DropdownMenuItem(value:v,child:Text(v))).toList(),onChanged:(v)=>setState(()=>type=v??type)),const SizedBox(height:15),FilledButton.icon(onPressed:submit,icon:const Icon(Icons.send),label:const Text('إرسال للمراجعة'))];}Widget field(TextEditingController x,String l)=>Padding(padding:const EdgeInsets.only(top:10),child:TextField(controller:x,decoration:InputDecoration(labelText:l,filled:true,fillColor:Colors.white12)));void submit(){final yr=int.tryParse(y.text);if(n.text.trim().isEmpty||p.text.trim().isEmpty||yr==null)return;widget.onSubmit(Car(n.text.trim(),yr,p.text.trim(),c.text.trim(),type,seller:widget.name??'بائع'));}}
class Details extends StatelessWidget{final Car car;final bool favorite;final VoidCallback onFavorite;const Details({super.key,required this.car,required this.favorite,required this.onFavorite});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('تفاصيل السيارة')),body:ListView(padding:const EdgeInsets.all(18),children:[Container(height:190,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20)),child:const Icon(Icons.directions_car,size:120,color:navy)),const SizedBox(height:15),Text(car.name,style:const TextStyle(fontSize:28,fontWeight:FontWeight.bold)),Text(car.price,style:const TextStyle(fontSize:22,color:green,fontWeight:FontWeight.bold)),Card(color:Colors.white,child:Padding(padding:const EdgeInsets.all(15),child:Text('السنة: ${car.year}\nالمدينة: ${car.city}\nالنوع: ${car.type}\nالبائع: ${car.seller}',style:const TextStyle(color:Colors.black87,height:1.7)))),FilledButton.icon(onPressed:onFavorite,icon:Icon(favorite?Icons.favorite:Icons.favorite_border),label:Text(favorite?'إزالة من المفضلة':'حفظ في المفضلة'))]));}

class Admin extends StatefulWidget{final List<PendingAd> pending;final List<User> users;final void Function(int) onApprove,onReject;final ValueChanged<Car> onPost;const Admin({super.key,required this.pending,required this.users,required this.onApprove,required this.onReject,required this.onPost});@override State<Admin> createState()=>_AdminState();}
class _AdminState extends State<Admin>{int tab=0;@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('تحكم بالتطبيق وبياناته والمستخدمين')),body:ListView(padding:const EdgeInsets.all(16),children:[const Text('لوحة تحكم BUKO',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const Text('الأدمن يستطيع نشر المنشورات مباشرة.',style:TextStyle(color:Colors.white70)),const SizedBox(height:15),SegmentedButton<int>(segments:const[ButtonSegment(value:0,label:Text('طلبات المراجعة')),ButtonSegment(value:1,label:Text('إضافة منشور')),ButtonSegment(value:2,label:Text('المستخدمون'))],selected:{tab},onSelectionChanged:(s)=>setState(()=>tab=s.first)),const SizedBox(height:15),if(tab==0)reviews(),if(tab==1)AdminPost(onPost:widget.onPost),if(tab==2)users()]));Widget reviews()=>widget.pending.isEmpty?const Card(child:Padding(padding:EdgeInsets.all(25),child:Center(child:Text('لا توجد طلبات معلقة')))):Column(children:List.generate(widget.pending.length,(i){final p=widget.pending[i];return Card(color:Colors.white,child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(p.car.name,style:const TextStyle(color:Colors.black87,fontSize:19,fontWeight:FontWeight.bold)),Text('${p.car.year} • ${p.car.city} • ${p.car.type}',style:const TextStyle(color:Colors.black54)),Text(p.car.price,style:const TextStyle(color:green,fontWeight:FontWeight.bold)),Row(children:[Expanded(child:FilledButton.icon(onPressed:(){widget.onApprove(i);setState((){});},icon:const Icon(Icons.check),label:const Text('موافقة ونشر'))),const SizedBox(width:8),Expanded(child:OutlinedButton.icon(onPressed:(){widget.onReject(i);setState((){});},icon:const Icon(Icons.close),label:const Text('رفض')))])])));}));Widget users()=>Column(children:[Card(child:ListTile(title:const Text('المستخدمون'),trailing:Text('${widget.users.length}'))),...widget.users.map((u)=>Card(color:Colors.white,child:ListTile(title:Text(u.name,style:const TextStyle(color:Colors.black87)),subtitle:Text('${u.email} • ${u.role=="seller"?"بائع":"مشتري"}',style:const TextStyle(color:Colors.black54))))) ]);}
class AdminPost extends StatefulWidget{final ValueChanged<Car> onPost;const AdminPost({super.key,required this.onPost});@override State<AdminPost> createState()=>_AdminPostState();}
class _AdminPostState extends State<AdminPost>{final n=TextEditingController(),y=TextEditingController(text:'2024'),p=TextEditingController(),c=TextEditingController(text:'القاهرة');String type='سيدان';@override void dispose(){n.dispose();y.dispose();p.dispose();c.dispose();super.dispose();}@override Widget build(BuildContext x)=>Card(child:Padding(padding:const EdgeInsets.all(15),child:Column(children:[const Align(alignment:Alignment.centerRight,child:Text('إضافة منشور الإدارة',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold))),f(n,'اسم السيارة'),f(y,'السنة'),f(p,'السعر'),f(c,'المدينة'),DropdownButtonFormField<String>(initialValue:type,items:const['سيدان','دفع رباعي','بيك أب'].map((v)=>DropdownMenuItem(value:v,child:Text(v))).toList(),onChanged:(v)=>setState(()=>type=v??type)),const SizedBox(height:15),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:post,icon:const Icon(Icons.publish),label:const Text('نشر مباشرة'))])));Widget f(TextEditingController x,String l)=>Padding(padding:const EdgeInsets.only(top:8),child:TextField(controller:x,decoration:InputDecoration(labelText:l)));void post(){final yr=int.tryParse(y.text);if(n.text.trim().isEmpty||p.text.trim().isEmpty||yr==null)return;widget.onPost(Car(n.text.trim(),yr,p.text.trim(),c.text.trim(),type,seller:'إدارة BUKO'));}}
